Repository rubpergar/piripi-hub, pull requests merged in 2024-12, with the labels that each got.

#26 feat: add download all datasets in all formats #7 #18
  app/modules/dataset/models.py
  app/modules/dataset/repositories.py
  app/modules/dataset/services.py
  app/modules/dataset/tests/locustfile.py
  app/modules/dataset/tests/test_selenium_download_all.py
  app/modules/dataset/tests/test_unit.py
  core/services/BaseService.py
  uploads/user_1/dataset_1/file1.uvl
  uploads/user_1/dataset_1/file2.uvl
  uploads/user_1/dataset_1/file3.uvl
  uploads/user_1/dataset_3/file7.uvl
  uploads/user_1/dataset_3/file8.uvl
  uploads/user_1/dataset_3/file9.uvl
  uploads/user_2/dataset_2/file4.uvl
  uploads/user_2/dataset_2/file5.uvl
  uploads/user_2/dataset_2/file6.uvl
  uploads/user_2/dataset_4/file10.uvl
  uploads/user_2/dataset_4/file11.uvl
  uploads/user_2/dataset_4/file12.uvl
Labels: enhancement, test

#28 feat: WI6-RememberMyPassword
  app/__init__.py
  app/modules/auth/forms.py
  app/modules/auth/routes.py
  app/modules/auth/templates/auth/forgot_password.html
  app/modules/auth/templates/auth/login_form.html
  app/modules/auth/templates/auth/password_recovery_success.html
  app/modules/auth/templates/auth/recover_password_form.html
  app/modules/auth/templates/auth/reset_password.html
  requirements.txt
Labels: enhancement

#32 feat: develop integration into main
  .github/workflows/codacy.yml
  .moduleignore
  app/__init__.py
  app/modules/auth/forms.py
  app/modules/auth/routes.py
  app/modules/auth/templates/auth/forgot_password.html
  app/modules/auth/templates/auth/login_form.html
  app/modules/auth/templates/auth/password_recovery_success.html
  app/modules/auth/templates/auth/recover_password_form.html
  app/modules/auth/templates/auth/reset_password.html
  app/modules/dataset/forms.py
  app/modules/dataset/models.py
  app/modules/dataset/repositories.py
  app/modules/dataset/routes.py
  app/modules/dataset/services.py
  app/modules/dataset/templates/dataset/view_dataset.html
  app/modules/dataset/templates/rate/create.html
  app/modules/dataset/templates/rate/edit.html
  app/modules/dataset/templates/rate/index.html
  app/modules/dataset/tests/locustfile.py
  app/modules/dataset/tests/test_rate.py
  app/modules/dataset/tests/test_rate_selenium.py
  app/modules/dataset/tests/test_selenium_download_all.py
  app/modules/dataset/tests/test_unit.py
  app/modules/explore/assets/scripts.js
  app/modules/explore/repositories.py
  app/modules/explore/services.py
  app/modules/explore/templates/explore/index.html
  app/modules/hubfile/routes.py
  app/modules/profile/routes.py
  app/modules/profile/templates/profile/summary.html
  app/static/css/style.css
  app/templates/base_template.html
  core/blueprints/base_blueprint.py
  core/services/BaseService.py
  requirements.txt
  uploads/user_1/dataset_1/file1.uvl
  uploads/user_1/dataset_1/file2.uvl
  uploads/user_1/dataset_1/file3.uvl
  uploads/user_1/dataset_3/file7.uvl
  uploads/user_1/dataset_3/file8.uvl
  uploads/user_1/dataset_3/file9.uvl
  uploads/user_2/dataset_2/file4.uvl
  uploads/user_2/dataset_2/file5.uvl
  uploads/user_2/dataset_2/file6.uvl
  uploads/user_2/dataset_4/file10.uvl
  uploads/user_2/dataset_4/file11.uvl
  uploads/user_2/dataset_4/file12.uvl
Labels: enhancement

#42 test: add tests for WI2-AdvancedFiltering
  app/modules/explore/tests/locustfile.py
  app/modules/explore/tests/test_selenium_advanced_filtering_features.py
  app/modules/explore/tests/test_selenium_advanced_filtering_models.py
  app/modules/explore/tests/test_selenium_advanced_filtering_query.py
  app/modules/explore/tests/test_unit.py
Labels: test

#41 test: add tests for WI6-RememberMyPassword
  app/modules/auth/tests/locustfile.py
  app/modules/auth/tests/test_selenium_remember_my_password_1.py
  app/modules/auth/tests/test_unit.py
Labels: test

#40 test: add tests for WI1-SearchQueries
  app/modules/hubfile/tests/locustfile.py
  app/modules/hubfile/tests/test_selenium_search_queries.py
  app/modules/hubfile/tests/test_unit_search_queries.py
Labels: test

#43 feat: wi3 download all + refactor tests
  app/modules/dataset/repositories.py
  app/modules/dataset/routes.py
  app/modules/dataset/services.py
  app/modules/dataset/tests/test_unit.py
  app/templates/base_template.html
Labels: test

#47 ci: add migrations workflow
  .github/workflows/migrations.yml
  .github/workflows/validate_yaml.yml
  .yamllint
Labels: ci

#51 fix: no login public data access
  app/modules/profile/routes.py
Labels: bug

#61 fix: updated __init__ to allow deploy
  app/__init__.py
Labels: ci

#56 feat: added render workflow
  .github/workflows/render.yml
Labels: ci
